# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc/proto/scc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14grpc/proto/scc.proto\x12\x03scc\"1\n\rHealthRequest\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message\"/\n\x0bHealthReply\x12\x14\n\x07message\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_message29\n\x07\x43ommand\x12.\n\x06Health\x12\x12.scc.HealthRequest\x1a\x10.scc.HealthReplyb\x06proto3')



_HEALTHREQUEST = DESCRIPTOR.message_types_by_name['HealthRequest']
_HEALTHREPLY = DESCRIPTOR.message_types_by_name['HealthReply']
HealthRequest = _reflection.GeneratedProtocolMessageType('HealthRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHREQUEST,
  '__module__' : 'grpc.proto.scc_pb2'
  # @@protoc_insertion_point(class_scope:scc.HealthRequest)
  })
_sym_db.RegisterMessage(HealthRequest)

HealthReply = _reflection.GeneratedProtocolMessageType('HealthReply', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHREPLY,
  '__module__' : 'grpc.proto.scc_pb2'
  # @@protoc_insertion_point(class_scope:scc.HealthReply)
  })
_sym_db.RegisterMessage(HealthReply)

_COMMAND = DESCRIPTOR.services_by_name['Command']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HEALTHREQUEST._serialized_start=29
  _HEALTHREQUEST._serialized_end=78
  _HEALTHREPLY._serialized_start=80
  _HEALTHREPLY._serialized_end=127
  _COMMAND._serialized_start=129
  _COMMAND._serialized_end=186
# @@protoc_insertion_point(module_scope)
